import * as fs from "node:fs";
import * as path from "node:path";
import type { Message, Session } from "../intents/types.js";
import { queryLLM } from "../pipeline/llm.js";

interface UserSessionSummaryEntry {
  sessionId: string;
  createdAt: string;
  summary: string;
}

interface UserSummaryFile {
  schemaVersion: 1;
  userKey: string;
  summaries: UserSessionSummaryEntry[];
}

function toSafeFileName(userKey: string): string {
  return userKey.replace(/[^a-zA-Z0-9._-]/g, "_");
}

function buildSummaryPrompt(history: Message[]): Message[] {
  // Only user/assistant turns are summarized; system prompt text is excluded.
  const chatTranscript = history
    .filter((message) => message.role === "user" || message.role === "assistant")
    .map((message) => `${message.role.toUpperCase()}: ${message.content}`)
    .join("\n");

  return [
    {
      role: "system",
      content:
        "You summarize insurance support calls. Summarize only the provided chat. Do not include assumptions or external facts. Keep summary concise and structured in plain text with 4 sections: Customer Profile, Main Requests, Resolutions/Outcomes, Follow-ups.",
    },
    {
      role: "user",
      content: `Summarize this session chat only:\n\n${chatTranscript}`,
    },
  ];
}

export async function summarizeSessionHistory(history: Message[]): Promise<string> {
  if (history.length === 0) {
    return "No conversation content captured for this session.";
  }

  try {
    // Summary is intentionally compact because this is fed back into future prompts.
    const llmResponse = await queryLLM(buildSummaryPrompt(history));
    const cleaned = llmResponse.trim();
    return cleaned.length > 0 ? cleaned : "No summary generated by LLM.";
  } catch (error) {
    console.error("[SUMMARY] Failed to generate session summary:", error);
    return "Summary unavailable due to LLM error.";
  }
}

export class SummaryStore {
  private readonly baseDir: string;

  constructor(baseDir: string = path.join(process.cwd(), "data", "summaries")) {
    this.baseDir = baseDir;
    fs.mkdirSync(this.baseDir, { recursive: true });
  }

  appendSummary(session: Session, summary: string): void {
    const filePath = path.join(this.baseDir, `${toSafeFileName(session.userKey)}.json`);
    const tempPath = `${filePath}.tmp`;
    const payload = this.loadOrCreate(session.userKey);

    payload.summaries.push({
      sessionId: session.sessionId,
      createdAt: new Date().toISOString(),
      summary,
    });

    fs.writeFileSync(tempPath, JSON.stringify(payload, null, 2), "utf-8");
    fs.renameSync(tempPath, filePath);
  }

  getLatestSummary(userKey: string): string | null {
    const payload = this.loadOrCreate(userKey);
    if (payload.summaries.length === 0) {
      return null;
    }

    const latestSummary = payload.summaries[payload.summaries.length - 1];
    return latestSummary?.summary ?? null;
  }

  getAllSummariesAsContext(userKey: string): string | null {
    const payload = this.loadOrCreate(userKey);
    if (payload.summaries.length === 0) {
      return null;
    }

    const combined = payload.summaries
      .map((entry, index) => {
        // Numbered blocks help prompt readability when many sessions exist.
        const summaryText = entry.summary.trim();
        if (summaryText.length === 0) {
          return "";
        }

        return `Session ${index + 1} (${entry.createdAt})\n${summaryText}`;
      })
      .filter((chunk) => chunk.length > 0)
      .join("\n\n");

    return combined.length > 0 ? combined : null;
  }

  private loadOrCreate(userKey: string): UserSummaryFile {
    const filePath = path.join(this.baseDir, `${toSafeFileName(userKey)}.json`);

    if (!fs.existsSync(filePath)) {
      return {
        schemaVersion: 1,
        userKey,
        summaries: [],
      };
    }

    try {
      const raw = fs.readFileSync(filePath, "utf-8");
      const parsed = JSON.parse(raw) as Partial<UserSummaryFile>;
      if (
        parsed.schemaVersion === 1 &&
        parsed.userKey === userKey &&
        Array.isArray(parsed.summaries)
      ) {
        return {
          schemaVersion: 1,
          userKey,
          summaries: parsed.summaries,
        };
      }
    } catch {
      console.error("[SUMMARY] Failed to read existing summary file. Recreating file.");
    }

    return {
      schemaVersion: 1,
      userKey,
      summaries: [],
    };
  }
}
